apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: composites3buckets.example.com
spec:
  group: example.com
  names:
    kind: CompositeS3Bucket
    plural: composites3buckets
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    bucketName:
                      type: string
                    tags:
                      type: object
                      additionalProperties: true
                  required:
                    - bucketName
