apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-composite-s3-bucket-tags
spec:
  validationFailureAction: Enforce
  rules:
    - name: require-environment-tag
      match:
        resources:
          kinds:
            - CompositeS3Bucket
      validate:
        message: "Composite S3 buckets must have an 'environment' tag."
        pattern:
          spec:
            parameters:
              tags:
                environment: "?*"
