name: AWS Provider Configuration

on:
  workflow_call:

jobs:
  aws-provider-config:
    name: "AWS Provider Configuration"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    defaults:
      run:
        working-directory: ./.crossplane/providers/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
          kubectl config set-context --current --namespace=default

      - name: Create AWS Credentials Secret
        run: |
          sed -i "s/{{AWS_ACCESS_KEY_ID}}/${{ secrets.AWS_ACCESS_KEY_ID }}/g" aws-provider-secret.yaml
          sed -i "s/{{AWS_SECRET_ACCESS_KEY}}/${{ secrets.AWS_SECRET_ACCESS_KEY }}/g" aws-provider-secret.yaml
          kubectl apply -f aws-provider-secret.yaml

      - name: Apply AWS Provider Configuration
        run: kubectl apply -f aws-provider.yaml
