name: AWS Provider Configuration

on:
  workflow_call:

jobs:
  aws-provider-config:
    name: "AWS Provider Configuration"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
          kubectl config set-context --current --namespace=default

      - name: Create AWS Credentials Secret
        run: |
          kubectl create secret generic aws-credentials -n crossplane-system \
            --from-literal=aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply AWS Provider Configuration
        run: kubectl apply -f ./.crossplane/providers/aws-provider.yaml
