name: Composition Apply

on:
  workflow_call:

jobs:
  composition-apply:
    name: "Composition Apply"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
          kubectl config set-context --current --namespace=default

      - name: Apply Composite Resource Definition
        run: kubectl apply -f compositions/composite-s3-bucket-xrd.yaml
      - name: Apply Composition
        run: kubectl apply -f compositions/aws-s3-composition.yaml
