name: Crossplane Test

on:
  workflow_call:

jobs:
  crossplane-test:
    name: "Crossplane Test"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Apply S3 Bucket
        run: kubectl apply -f managed-resources/composite-s3-bucket.yaml
      - name: Verify S3 Bucket
        run: kubectl wait --for=condition=ready composites3buckets.example.com/crossplane-s3-bucket --timeout=120s
