name: Crossplane Test

on:
  workflow_call:

jobs:
  crossplane-test:
    name: "Crossplane Test"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
          kubectl config set-context --current --namespace=default

      - name: Apply S3 Bucket
        run: kubectl apply -f ./.crossplane/managed-resources/composite-s3-bucket.yaml
      - name: Verify S3 Bucket
        run: kubectl wait --for=condition=ready composites3bucket.example.com/crossplane-s3-bucket --timeout 5m
