name: Crossplane Installation

on:
  workflow_call:

jobs:
  crossplane-install:
    name: "Crossplane Installation"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Install Crossplane
        run: |
          kubectl create namespace crossplane-system --dry-run=client -o yaml | kubectl apply -f -
          helm repo add crossplane-stable https://charts.crossplane.io/stable
          helm repo update
          helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --version 1.14.0
          kubectl wait --for=condition=available deployment/crossplane -n crossplane-system --timeout=120s
