name: Kyverno Installation

on:
  workflow_call:

jobs:
  kyverno-install:
    name: "Kyverno Installation"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Install Kyverno
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm repo update
          helm install kyverno kyverno/kyverno --namespace kyverno --create-namespace
          kubectl wait --for=condition=available deployment/kyverno -n kyverno --timeout=120s
