name: Kyverno Test

on:
  workflow_call:

jobs:
  kyverno-test:
    name: "Kyverno Test"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
          kubectl config set-context --current --namespace=default

      - name: Kyverno Policy Apply
        run: kubectl apply -f policies/validate-s3-tags.yaml
      - name: Kyverno Policy Enforcement Test
        run: |
          kubectl apply -f managed-resources/composite-s3-bucket.yaml
          kubectl wait --for=condition=ready composites3bucket.example.com/composite-bucket-crossplane-demo
          sed -i '/environment: dev/d' managed-resources/composite-s3-bucket.yaml
          if kubectl apply -f managed-resources/composite-s3-bucket.yaml; then
          echo "Policy enforcement failed: Non-compliant resource was allowed."
          exit 1
          else
          echo "Policy enforcement succeeded: Non-compliant resource was blocked."
          fi
