name: Kyverno Test

on:
  workflow_call:

jobs:
  kyverno-test:
    name: "Kyverno Test"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Kyverno Policy Apply
        run: kubectl apply -f policies/validate-s3-tags.yaml
      - name: Kyverno Policy Enforcement Test
        run: |
          kubectl apply -f managed-resources/composite-s3-bucket.yaml
          kubectl wait --for=condition=ready composites3bucket.example.com/composite-bucket-crossplane-demo --timeout=120s
          sed -i '/environment: dev/d' managed-resources/composite-s3-bucket.yaml
          if kubectl apply -f managed-resources/composite-s3-bucket.yaml; then
          echo "Policy enforcement failed: Non-compliant resource was allowed."
          exit 1
          else
          echo "Policy enforcement succeeded: Non-compliant resource was blocked."
          fi
