name: Kyverno Test

on:
  workflow_call:

jobs:
  kyverno-test:
    name: "Kyverno Test"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
          kubectl config set-context --current --namespace=default

      - name: Kyverno Policy Apply
        run: kubectl apply -f ./.crossplane/policies/validate-s3-tags.yaml
      - name: Kyverno Policy Enforcement Test
        run: |
          kubectl apply -f ./.crossplane/managed-resources/composite-s3-bucket.yaml
          kubectl wait --for=condition=ready composites3bucket.example.com/composite-bucket-crossplane-demo --timeout 5m
          sed -i '/^\s*environment: production/d' ./.crossplane/managed-resources/composite-s3-bucket.yaml
          if kubectl apply -f ./.crossplane/managed-resources/composite-s3-bucket.yaml; then
            echo "Kyverno Policy enforcement failed: Non-compliant resource allowed"
            exit 1
          else
            echo "Kyverno Policy enforcement succeeded: Non-compliant resource blocked"
          fi
