name: Kyverno Installation

on:
  workflow_call:

jobs:
  kyverno-install:
    name: "Kyverno Installation"
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
          kubectl config set-context --current --namespace=default

      - name: Install Kyverno
        run: |
          kubectl create namespace kyverno --dry-run=client -o yaml | kubectl apply -f -
          if kubectl get deployment kyverno-admission-controller -n kyverno >/dev/null 2>&1 && \
            kubectl wait --for=condition=available deployment/kyverno-admission-controller -n kyverno >/dev/null --timeout 5m 2>&1; then
            echo "Kyverno is already installed and healthy, skipping installation"
          else
            echo "Kyverno not found or not healthy, installing..."
            helm repo add kyverno https://kyverno.github.io/kyverno/
            helm repo update
            if helm list -n kyverno | grep -q "kyverno"; then
              echo "Removing existing Helm release 'kyverno'..."
              helm uninstall kyverno -n kyverno --wait || echo "Uninstall failed, proceeding with installation"
            fi
            helm install kyverno kyverno/kyverno --namespace kyverno --create-namespace
          fi
          kubectl wait --for=condition=available deployment/kyverno-admission-controller -n kyverno --timeout 5m
