name: Crossplane and Kyverno deployment

on:
  push:
    branches: [ "main" ]

jobs:
  aws-eks-setup:
    name: "AWS EKS Setup"
    uses: ./.github/workflows/aws-eks-access.yml
    secrets: inherit
  crossplane-install:
    name: "Crossplane Installation"
    needs: [ aws-eks-setup ]
    uses: ./.github/workflows/crossplane-install.yml
    secrets: inherit
  aws-provider-config:
    name: "AWS Provider Setup"
    needs: [ crossplane-install ]
    uses: ./.github/workflows/aws-provider-config.yml
    secrets: inherit
  composition-apply:
    name: "Composition Apply"
    needs: [ aws-provider-config ]
    uses: ./.github/workflows/composition-apply.yml
    secrets: inherit
  kyverno-install:
    name: "Kyverno Installation"
    needs: [ composition-apply ]
    uses: ./.github/workflows/kyverno-install.yml
    secrets: inherit
  crossplane-test:
    name: "Crossplane Test"
    needs: [ kyverno-install ]
    uses: ./.github/workflows/crossplane-test.yml
    secrets: inherit
  kyverno-test:
    name: "Kyverno Test"
    needs: [ crossplane-test ]
    uses: ./.github/workflows/kyverno-test.yml
    secrets: inherit
